### ISSUE TITLE
What is this repository used for?

### ISSUE THREAD

**Issue by Lingrui98** [sdogsq/UCAS-Database-LAB2-TrainBookingSystem#1]
Thank you for your great effort carrying your younger schoolmates!

**Comment by sdogsq** [comment]
Database class now faces huge opportunities for peace, stability, prosperity and development. As a saying in Laos goes, “One trunk does not make a fence. And a village will not be a good place without every villager working for it together.” I hope that parties will work together to promote steady progress of database cooperation and contribute to peace, stability and enduring prosperity of this class, the benefit of students of all majors.
